[workspace]
resolver = "2"
members = [
    "crates/meshtui",
    "crates/meshtui-core",
    "crates/meshtui-render",
    "crates/meshtui-term",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/madsendennis/meshtui"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
glam = { version = "0.29", features = ["serde"] }
rayon = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
memmap2 = "0.9"
image = { version = "0.25", default-features = false, features = ["png"] }
ratatui = "0.29"
crossterm = "0.28"
regex = "1"
dirs = "6"
criterion = { version = "0.5", features = ["html_reports"] }
meshtui-core = { path = "crates/meshtui-core" }
meshtui-render = { path = "crates/meshtui-render" }
meshtui-term = { path = "crates/meshtui-term" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
